stages:
  - test
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deployment:
  image: MCR.microsoft.com/dotnet/sdk:6.0
  stage: deploy
  before_script:
    - apt-get update
    - apt-get install zip -y
  script:
    - cd MazeGame
    - dotnet publish -c Release -o publish_output
    - cd publish_output
    - zip -r MazeGame.zip .
  artifacts:
    paths:
      - MazeGame.zip
    expire_in: "2 weeks"
