default:
  image: mcr.microsoft.com/dotnet/sdk:6.0
stages:
  - test
  - deploy

unit-test:
  stage: test
  script:
    - cd MazeRecursionTests
    - 'dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
  artifacts:
    when: always
    paths:
       - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml

    expire_in: "1 week"


deployment:
  stage: deploy
  before_script:
    - apt-get update
    - apt-get install zip -y
  script:
    - cd MazeGame
    - dotnet publish -o publish_output
    - zip -r MazeGame.zip publish_output/.
  artifacts:
    paths:
      - MazeGame.zip
    expire_in: "2 weeks"
